import { setup, createMachine, assign } from "xstate";

export const workflowMachine = setup({
  types: {
    context: {} as any,
    events: {} as any,
  } as any,
  actions: {
    setInputs: assign((context, event: any) => {
      const { form } = context;
      const { inputs } = event.data;

      context.form.inputs = {
        ...form.inputs,
        ...inputs,
      };
    }),
    setFiles: assign((context, event: any) => {
      const { form } = context;
      const { files } = event.data;
      context.form.files = [...form.files, ...files];
    }),
    setToggle: assign((context: any, event: any) => {
      //event: { target: panel, path: showSingleRunPanel }
      const { target, path } = event.data;
      context[target][path] = !context[target][path] as boolean;
    }),
  },
  actors: {},
  guards: {},
}).createMachine({
  id: "workflowMachine",
  initial: "idle",
  context: {
    form: {
      inputs: {},
      files: [],
    },
    node: {
      showSingleRunPanel: false,
      nodesDefaultConfigs: {
        llm: {
          prompt_templates: {
            chat_model: {
              prompts: [
                {
                  role: "system",
                  text: "You are a helpful AI assistant.",
                  edition_type: "basic",
                },
              ],
            },
            completion_model: {
              conversation_histories_role: {
                user_prefix: "Human",
                assistant_prefix: "Assistant",
              },
              prompt: {
                text: "Here are the chat histories between human and assistant, inside <histories></histories> XML tags.\n\n<histories>\n{{#histories#}}\n</histories>\n\n\nHuman: {{#sys.query#}}\n\nAssistant:",
                edition_type: "basic",
              },
              stop: ["Human:"],
            },
          },
        },
        code: {
          variables: [
            {
              variable: "arg1",
              value_selector: [],
            },
            {
              variable: "arg2",
              value_selector: [],
            },
          ],
          code_language: "python3",
          code: '\ndef main(arg1: str, arg2: str) -> dict:\n    return {\n        "result": arg1 + arg2,\n    }\n',
          outputs: {
            result: {
              type: "string",
              children: null,
            },
          },
        },
        "template-transform": {
          variables: [
            {
              variable: "arg1",
              value_selector: [],
            },
          ],
          template: "{{ arg1 }}",
        },
        "question-classifier": {
          instructions: "",
        },
        "http-request": {
          method: "get",
          authorization: {
            type: "no-auth",
          },
          body: {
            type: "none",
          },
          timeout: {
            connect: 300,
            read: 600,
            write: 600,
            max_connect_timeout: 300,
            max_read_timeout: 600,
            max_write_timeout: 600,
          },
        },
        iteration: {
          is_parallel: false,
          parallel_nums: 10,
          error_handle_mode: "terminated",
        },
        undefined: {},
      },
      nodeAnimation: false,
      candidateNode: undefined,
      nodeMenu: undefined,
      showAssignVariablePopup: undefined,
      hoveringAssignVariableGroupId: undefined,
      connectingNodePayload: undefined,
      enteringNodePayload: undefined,
      iterTimes: 1,
      loopTimes: 1,
      iterParallelLogMap: new Map(),
    },
    chatVariable: {
      showGlobalVariablePanel: false,
      showDebugAndPreviewPanel: undefined,
      showEnvPanel: undefined,
      showChatVariablePanel: undefined,
      conversationVariables: [],
    },
    envVariable: {
      showEnvPanel: false,
      environmentVariables: [],
      envSecrets: {},
    },
    helpLine: {
      helpLineHorizontal: undefined,
      helpLineVertical: undefined,
    },
    history: {
      historyWorkflowData: undefined,
      showRunHistory: false,
      versionHistory: [],
    },
    panel: {
      panelWidth: 420,
      showFeaturesPanel: false,
      showWorkflowVersionHistoryPanel: false,
      showInputsPanel: false,
      showDebugAndPreviewPanel: false,
      panelMenu: undefined,
    },
    tool: {
      buildInTools: [
        {
          id: "code",
          author: "Dify",
          name: "code",
          plugin_id: null,
          plugin_unique_identifier: "",
          description: {
            zh_Hans: "运行一段代码并返回结果。",
            en_US: "Run a piece of code and get the result back.",
            pt_BR: "Execute um trecho de código e obtenha o resultado de volta.",
            ja_JP: "Run a piece of code and get the result back.",
          },
          icon: "http://127.0.0.1:5001/console/api/workspaces/current/tool-provider/builtin/code/icon",
          label: {
            zh_Hans: "代码解释器",
            en_US: "Code Interpreter",
            pt_BR: "Interpretador de Código",
            ja_JP: "Code Interpreter",
          },
          type: "builtin",
          team_credentials: {},
          is_team_authorization: true,
          allow_delete: false,
          tools: [
            {
              author: "Dify",
              name: "simple_code",
              label: {
                en_US: "Code Interpreter",
                zh_Hans: "代码解释器",
                pt_BR: "Interpretador de Código",
                ja_JP: "Code Interpreter",
              },
              description: {
                en_US:
                  "Run code and get the result back. When you're using a lower quality model, please make sure there are some tips help LLM to understand how to write the code.",
                zh_Hans: "运行一段代码并返回结果。当您使用较低质量的模型时，请确保有一些提示帮助LLM理解如何编写代码。",
                pt_BR:
                  "Execute um trecho de código e obtenha o resultado de volta. quando você estiver usando um modelo de qualidade inferior, certifique-se de que existam algumas dicas para ajudar o LLM a entender como escrever o código.",
                ja_JP:
                  "Run code and get the result back. When you're using a lower quality model, please make sure there are some tips help LLM to understand how to write the code.",
              },
              parameters: [
                {
                  name: "language",
                  label: {
                    en_US: "Language",
                    zh_Hans: "语言",
                    pt_BR: "Idioma",
                    ja_JP: "Language",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: true,
                  default: null,
                  min: null,
                  max: null,
                  precision: null,
                  options: [
                    {
                      value: "python3",
                      label: {
                        en_US: "Python3",
                        zh_Hans: "Python3",
                        pt_BR: "Python3",
                        ja_JP: "Python3",
                      },
                    },
                    {
                      value: "javascript",
                      label: {
                        en_US: "JavaScript",
                        zh_Hans: "JavaScript",
                        pt_BR: "JavaScript",
                        ja_JP: "JavaScript",
                      },
                    },
                  ],
                  type: "string",
                  human_description: {
                    en_US: "The programming language of the code",
                    zh_Hans: "代码的编程语言",
                    pt_BR: "A linguagem de programação do código",
                    ja_JP: "The programming language of the code",
                  },
                  form: "llm",
                  llm_description: 'language of the code, only "python3" and "javascript" are supported',
                },
                {
                  name: "code",
                  label: {
                    en_US: "Code",
                    zh_Hans: "代码",
                    pt_BR: "Código",
                    ja_JP: "Code",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: true,
                  default: null,
                  min: null,
                  max: null,
                  precision: null,
                  options: [],
                  type: "string",
                  human_description: {
                    en_US: "The code to be executed",
                    zh_Hans: "要执行的代码",
                    pt_BR: "O código a ser executado",
                    ja_JP: "The code to be executed",
                  },
                  form: "llm",
                  llm_description:
                    "code to be executed, only native packages are allowed, network/IO operations are disabled.",
                },
              ],
              labels: ["productivity"],
              output_schema: null,
            },
          ],
          labels: ["productivity"],
        },
        {
          id: "time",
          author: "Dify",
          name: "time",
          plugin_id: null,
          plugin_unique_identifier: "",
          description: {
            zh_Hans: "一个用于获取当前时间的工具。",
            en_US: "A tool for getting the current time.",
            pt_BR: "A tool for getting the current time.",
            ja_JP: "A tool for getting the current time.",
          },
          icon: "http://127.0.0.1:5001/console/api/workspaces/current/tool-provider/builtin/time/icon",
          label: {
            zh_Hans: "时间",
            en_US: "CurrentTime",
            pt_BR: "CurrentTime",
            ja_JP: "CurrentTime",
          },
          type: "builtin",
          team_credentials: {},
          is_team_authorization: true,
          allow_delete: false,
          tools: [
            {
              author: "Dify",
              name: "current_time",
              label: {
                en_US: "Current Time",
                zh_Hans: "获取当前时间",
                pt_BR: "Current Time",
                ja_JP: "Current Time",
              },
              description: {
                en_US: "A tool for getting the current time.",
                zh_Hans: "一个用于获取当前时间的工具。",
                pt_BR: "A tool for getting the current time.",
                ja_JP: "A tool for getting the current time.",
              },
              parameters: [
                {
                  name: "format",
                  label: {
                    en_US: "Format",
                    zh_Hans: "格式",
                    pt_BR: "Format",
                    ja_JP: "Format",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: false,
                  default: "%Y-%m-%d %H:%M:%S",
                  min: null,
                  max: null,
                  precision: null,
                  options: [],
                  type: "string",
                  human_description: {
                    en_US: "Time format in strftime standard.",
                    zh_Hans: "strftime 标准的时间格式。",
                    pt_BR: "Time format in strftime standard.",
                    ja_JP: "Time format in strftime standard.",
                  },
                  form: "form",
                  llm_description: null,
                },
                {
                  name: "timezone",
                  label: {
                    en_US: "Timezone",
                    zh_Hans: "时区",
                    pt_BR: "Timezone",
                    ja_JP: "Timezone",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: false,
                  default: "UTC",
                  min: null,
                  max: null,
                  precision: null,
                  options: [
                    {
                      value: "UTC",
                      label: {
                        en_US: "UTC",
                        zh_Hans: "UTC",
                        pt_BR: "UTC",
                        ja_JP: "UTC",
                      },
                    },
                    {
                      value: "America/New_York",
                      label: {
                        en_US: "America/New_York",
                        zh_Hans: "美洲/纽约",
                        pt_BR: "America/New_York",
                        ja_JP: "America/New_York",
                      },
                    },
                    {
                      value: "America/Los_Angeles",
                      label: {
                        en_US: "America/Los_Angeles",
                        zh_Hans: "美洲/洛杉矶",
                        pt_BR: "America/Los_Angeles",
                        ja_JP: "America/Los_Angeles",
                      },
                    },
                    {
                      value: "America/Chicago",
                      label: {
                        en_US: "America/Chicago",
                        zh_Hans: "美洲/芝加哥",
                        pt_BR: "America/Chicago",
                        ja_JP: "America/Chicago",
                      },
                    },
                    {
                      value: "America/Sao_Paulo",
                      label: {
                        en_US: "America/Sao_Paulo",
                        zh_Hans: "美洲/圣保罗",
                        pt_BR: "América/São Paulo",
                        ja_JP: "America/Sao_Paulo",
                      },
                    },
                    {
                      value: "Asia/Shanghai",
                      label: {
                        en_US: "Asia/Shanghai",
                        zh_Hans: "亚洲/上海",
                        pt_BR: "Asia/Shanghai",
                        ja_JP: "Asia/Shanghai",
                      },
                    },
                    {
                      value: "Asia/Ho_Chi_Minh",
                      label: {
                        en_US: "Asia/Ho_Chi_Minh",
                        zh_Hans: "亚洲/胡志明市",
                        pt_BR: "Ásia/Ho Chi Minh",
                        ja_JP: "Asia/Ho_Chi_Minh",
                      },
                    },
                    {
                      value: "Asia/Tokyo",
                      label: {
                        en_US: "Asia/Tokyo",
                        zh_Hans: "亚洲/东京",
                        pt_BR: "Asia/Tokyo",
                        ja_JP: "Asia/Tokyo",
                      },
                    },
                    {
                      value: "Asia/Dubai",
                      label: {
                        en_US: "Asia/Dubai",
                        zh_Hans: "亚洲/迪拜",
                        pt_BR: "Asia/Dubai",
                        ja_JP: "Asia/Dubai",
                      },
                    },
                    {
                      value: "Asia/Kolkata",
                      label: {
                        en_US: "Asia/Kolkata",
                        zh_Hans: "亚洲/加尔各答",
                        pt_BR: "Asia/Kolkata",
                        ja_JP: "Asia/Kolkata",
                      },
                    },
                    {
                      value: "Asia/Seoul",
                      label: {
                        en_US: "Asia/Seoul",
                        zh_Hans: "亚洲/首尔",
                        pt_BR: "Asia/Seoul",
                        ja_JP: "Asia/Seoul",
                      },
                    },
                    {
                      value: "Asia/Singapore",
                      label: {
                        en_US: "Asia/Singapore",
                        zh_Hans: "亚洲/新加坡",
                        pt_BR: "Asia/Singapore",
                        ja_JP: "Asia/Singapore",
                      },
                    },
                    {
                      value: "Europe/London",
                      label: {
                        en_US: "Europe/London",
                        zh_Hans: "欧洲/伦敦",
                        pt_BR: "Europe/London",
                        ja_JP: "Europe/London",
                      },
                    },
                    {
                      value: "Europe/Berlin",
                      label: {
                        en_US: "Europe/Berlin",
                        zh_Hans: "欧洲/柏林",
                        pt_BR: "Europe/Berlin",
                        ja_JP: "Europe/Berlin",
                      },
                    },
                    {
                      value: "Europe/Moscow",
                      label: {
                        en_US: "Europe/Moscow",
                        zh_Hans: "欧洲/莫斯科",
                        pt_BR: "Europe/Moscow",
                        ja_JP: "Europe/Moscow",
                      },
                    },
                    {
                      value: "Australia/Sydney",
                      label: {
                        en_US: "Australia/Sydney",
                        zh_Hans: "澳大利亚/悉尼",
                        pt_BR: "Australia/Sydney",
                        ja_JP: "Australia/Sydney",
                      },
                    },
                    {
                      value: "Pacific/Auckland",
                      label: {
                        en_US: "Pacific/Auckland",
                        zh_Hans: "太平洋/奥克兰",
                        pt_BR: "Pacific/Auckland",
                        ja_JP: "Pacific/Auckland",
                      },
                    },
                    {
                      value: "Africa/Cairo",
                      label: {
                        en_US: "Africa/Cairo",
                        zh_Hans: "非洲/开罗",
                        pt_BR: "Africa/Cairo",
                        ja_JP: "Africa/Cairo",
                      },
                    },
                  ],
                  type: "select",
                  human_description: {
                    en_US: "Timezone",
                    zh_Hans: "时区",
                    pt_BR: "Timezone",
                    ja_JP: "Timezone",
                  },
                  form: "form",
                  llm_description: null,
                },
              ],
              labels: ["utilities"],
              output_schema: null,
            },
            {
              author: "zhuhao",
              name: "timezone_conversion",
              label: {
                en_US: "convert time to equivalent time zone",
                zh_Hans: "时区转换",
                pt_BR: "convert time to equivalent time zone",
                ja_JP: "convert time to equivalent time zone",
              },
              description: {
                en_US: "A tool to convert time to equivalent time zone",
                zh_Hans: "时区转换",
                pt_BR: "A tool to convert time to equivalent time zone",
                ja_JP: "A tool to convert time to equivalent time zone",
              },
              parameters: [
                {
                  name: "current_time",
                  label: {
                    en_US: "current time",
                    zh_Hans: "当前时间",
                    pt_BR: "current time",
                    ja_JP: "current time",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: true,
                  default: null,
                  min: null,
                  max: null,
                  precision: null,
                  options: [],
                  type: "string",
                  human_description: {
                    en_US: "current time, such as 2024-1-1 0:0:0",
                    zh_Hans: "当前时间, 比如2024-1-1 0:0:0",
                    pt_BR: "current time, such as 2024-1-1 0:0:0",
                    ja_JP: "current time, such as 2024-1-1 0:0:0",
                  },
                  form: "llm",
                  llm_description: null,
                },
                {
                  name: "current_timezone",
                  label: {
                    en_US: "Current Timezone",
                    zh_Hans: "当前时区",
                    pt_BR: "Current Timezone",
                    ja_JP: "Current Timezone",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: true,
                  default: "Asia/Shanghai",
                  min: null,
                  max: null,
                  precision: null,
                  options: [],
                  type: "string",
                  human_description: {
                    en_US: "Current Timezone, such as Asia/Shanghai",
                    zh_Hans: "当前时区, 比如Asia/Shanghai",
                    pt_BR: "Current Timezone, such as Asia/Shanghai",
                    ja_JP: "Current Timezone, such as Asia/Shanghai",
                  },
                  form: "llm",
                  llm_description: null,
                },
                {
                  name: "target_timezone",
                  label: {
                    en_US: "Target Timezone",
                    zh_Hans: "目标时区",
                    pt_BR: "Target Timezone",
                    ja_JP: "Target Timezone",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: true,
                  default: "Asia/Tokyo",
                  min: null,
                  max: null,
                  precision: null,
                  options: [],
                  type: "string",
                  human_description: {
                    en_US: "Target Timezone, such as Asia/Tokyo",
                    zh_Hans: "目标时区, 比如Asia/Tokyo",
                    pt_BR: "Target Timezone, such as Asia/Tokyo",
                    ja_JP: "Target Timezone, such as Asia/Tokyo",
                  },
                  form: "llm",
                  llm_description: null,
                },
              ],
              labels: ["utilities"],
              output_schema: null,
            },
            {
              author: "zhuhao",
              name: "timestamp_to_localtime",
              label: {
                en_US: "Timestamp to localtime",
                zh_Hans: "时间戳转换",
                pt_BR: "Timestamp to localtime",
                ja_JP: "Timestamp to localtime",
              },
              description: {
                en_US: "A tool for timestamp convert to localtime",
                zh_Hans: "时间戳转换",
                pt_BR: "A tool for timestamp convert to localtime",
                ja_JP: "A tool for timestamp convert to localtime",
              },
              parameters: [
                {
                  name: "timestamp",
                  label: {
                    en_US: "Timestamp",
                    zh_Hans: "时间戳",
                    pt_BR: "Timestamp",
                    ja_JP: "Timestamp",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: true,
                  default: null,
                  min: null,
                  max: null,
                  precision: null,
                  options: [],
                  type: "number",
                  human_description: {
                    en_US: "Timestamp",
                    zh_Hans: "时间戳",
                    pt_BR: "Timestamp",
                    ja_JP: "Timestamp",
                  },
                  form: "llm",
                  llm_description: null,
                },
                {
                  name: "timezone",
                  label: {
                    en_US: "Timezone",
                    zh_Hans: "时区",
                    pt_BR: "Timezone",
                    ja_JP: "Timezone",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: false,
                  default: "Asia/Shanghai",
                  min: null,
                  max: null,
                  precision: null,
                  options: [],
                  type: "string",
                  human_description: {
                    en_US: "Timezone, such as Asia/Shanghai",
                    zh_Hans: "时区, 比如Asia/Shanghai",
                    pt_BR: "Timezone, such as Asia/Shanghai",
                    ja_JP: "Timezone, such as Asia/Shanghai",
                  },
                  form: "llm",
                  llm_description: null,
                },
              ],
              labels: ["utilities"],
              output_schema: null,
            },
            {
              author: "Bowen Liang",
              name: "weekday",
              label: {
                en_US: "Weekday Calculator",
                zh_Hans: "星期几计算器",
                pt_BR: "Weekday Calculator",
                ja_JP: "Weekday Calculator",
              },
              description: {
                en_US: "A tool for calculating the weekday of a given date.",
                zh_Hans: "计算指定日期为星期几的工具。",
                pt_BR: "A tool for calculating the weekday of a given date.",
                ja_JP: "A tool for calculating the weekday of a given date.",
              },
              parameters: [
                {
                  name: "year",
                  label: {
                    en_US: "Year",
                    zh_Hans: "年",
                    pt_BR: "Year",
                    ja_JP: "Year",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: true,
                  default: null,
                  min: null,
                  max: null,
                  precision: null,
                  options: [],
                  type: "number",
                  human_description: {
                    en_US: "Year",
                    zh_Hans: "年",
                    pt_BR: "Year",
                    ja_JP: "Year",
                  },
                  form: "llm",
                  llm_description: null,
                },
                {
                  name: "month",
                  label: {
                    en_US: "Month",
                    zh_Hans: "月",
                    pt_BR: "Month",
                    ja_JP: "Month",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: true,
                  default: null,
                  min: null,
                  max: null,
                  precision: null,
                  options: [],
                  type: "number",
                  human_description: {
                    en_US: "Month",
                    zh_Hans: "月",
                    pt_BR: "Month",
                    ja_JP: "Month",
                  },
                  form: "llm",
                  llm_description: null,
                },
                {
                  name: "day",
                  label: {
                    en_US: "day",
                    zh_Hans: "日",
                    pt_BR: "day",
                    ja_JP: "day",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: true,
                  default: null,
                  min: null,
                  max: null,
                  precision: null,
                  options: [],
                  type: "number",
                  human_description: {
                    en_US: "day",
                    zh_Hans: "日",
                    pt_BR: "day",
                    ja_JP: "day",
                  },
                  form: "llm",
                  llm_description: null,
                },
              ],
              labels: ["utilities"],
              output_schema: null,
            },
            {
              author: "zhuhao",
              name: "localtime_to_timestamp",
              label: {
                en_US: "localtime to timestamp",
                zh_Hans: "获取时间戳",
                pt_BR: "localtime to timestamp",
                ja_JP: "localtime to timestamp",
              },
              description: {
                en_US: "A tool for localtime convert to timestamp",
                zh_Hans: "获取时间戳",
                pt_BR: "A tool for localtime convert to timestamp",
                ja_JP: "A tool for localtime convert to timestamp",
              },
              parameters: [
                {
                  name: "localtime",
                  label: {
                    en_US: "localtime",
                    zh_Hans: "本地时间",
                    pt_BR: "localtime",
                    ja_JP: "localtime",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: true,
                  default: null,
                  min: null,
                  max: null,
                  precision: null,
                  options: [],
                  type: "string",
                  human_description: {
                    en_US: "localtime, such as 2024-1-1 0:0:0",
                    zh_Hans: "本地时间, 比如2024-1-1 0:0:0",
                    pt_BR: "localtime, such as 2024-1-1 0:0:0",
                    ja_JP: "localtime, such as 2024-1-1 0:0:0",
                  },
                  form: "llm",
                  llm_description: null,
                },
                {
                  name: "timezone",
                  label: {
                    en_US: "Timezone",
                    zh_Hans: "时区",
                    pt_BR: "Timezone",
                    ja_JP: "Timezone",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: false,
                  default: "Asia/Shanghai",
                  min: null,
                  max: null,
                  precision: null,
                  options: [],
                  type: "string",
                  human_description: {
                    en_US: "Timezone, such as Asia/Shanghai",
                    zh_Hans: "时区, 比如Asia/Shanghai",
                    pt_BR: "Timezone, such as Asia/Shanghai",
                    ja_JP: "Timezone, such as Asia/Shanghai",
                  },
                  form: "llm",
                  llm_description: null,
                },
              ],
              labels: ["utilities"],
              output_schema: null,
            },
          ],
          labels: ["utilities"],
        },
        {
          id: "webscraper",
          author: "Dify",
          name: "webscraper",
          plugin_id: null,
          plugin_unique_identifier: "",
          description: {
            zh_Hans: "一个用于抓取网页的工具。",
            en_US: "Web Scrapper tool kit is used to scrape web",
            pt_BR: "Web Scrapper tool kit is used to scrape web",
            ja_JP: "Web Scrapper tool kit is used to scrape web",
          },
          icon: "http://127.0.0.1:5001/console/api/workspaces/current/tool-provider/builtin/webscraper/icon",
          label: {
            zh_Hans: "网页抓取",
            en_US: "WebScraper",
            pt_BR: "WebScraper",
            ja_JP: "WebScraper",
          },
          type: "builtin",
          team_credentials: {},
          is_team_authorization: true,
          allow_delete: false,
          tools: [
            {
              author: "Dify",
              name: "webscraper",
              label: {
                en_US: "Web Scraper",
                zh_Hans: "网页爬虫",
                pt_BR: "Web Scraper",
                ja_JP: "Web Scraper",
              },
              description: {
                en_US: "A tool for scraping webpages.",
                zh_Hans: "一个用于爬取网页的工具。",
                pt_BR: "A tool for scraping webpages.",
                ja_JP: "A tool for scraping webpages.",
              },
              parameters: [
                {
                  name: "url",
                  label: {
                    en_US: "URL",
                    zh_Hans: "网页链接",
                    pt_BR: "URL",
                    ja_JP: "URL",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: true,
                  default: null,
                  min: null,
                  max: null,
                  precision: null,
                  options: [],
                  type: "string",
                  human_description: {
                    en_US: "used for linking to webpages",
                    zh_Hans: "用于链接到网页",
                    pt_BR: "used for linking to webpages",
                    ja_JP: "used for linking to webpages",
                  },
                  form: "llm",
                  llm_description: "url for scraping",
                },
                {
                  name: "user_agent",
                  label: {
                    en_US: "User Agent",
                    zh_Hans: "User Agent",
                    pt_BR: "User Agent",
                    ja_JP: "User Agent",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: false,
                  default:
                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.1000.0 Safari/537.36",
                  min: null,
                  max: null,
                  precision: null,
                  options: [],
                  type: "string",
                  human_description: {
                    en_US: "used for identifying the browser.",
                    zh_Hans: "用于识别浏览器。",
                    pt_BR: "used for identifying the browser.",
                    ja_JP: "used for identifying the browser.",
                  },
                  form: "form",
                  llm_description: null,
                },
                {
                  name: "generate_summary",
                  label: {
                    en_US: "Whether to generate summary",
                    zh_Hans: "是否生成摘要",
                    pt_BR: "Whether to generate summary",
                    ja_JP: "Whether to generate summary",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: false,
                  default: "false",
                  min: null,
                  max: null,
                  precision: null,
                  options: [
                    {
                      value: "true",
                      label: {
                        en_US: "Yes",
                        zh_Hans: "是",
                        pt_BR: "Yes",
                        ja_JP: "Yes",
                      },
                    },
                    {
                      value: "false",
                      label: {
                        en_US: "No",
                        zh_Hans: "否",
                        pt_BR: "No",
                        ja_JP: "No",
                      },
                    },
                  ],
                  type: "boolean",
                  human_description: {
                    en_US: "If true, the crawler will only return the page summary content.",
                    zh_Hans: "如果启用，爬虫将仅返回页面摘要内容。",
                    pt_BR: "If true, the crawler will only return the page summary content.",
                    ja_JP: "If true, the crawler will only return the page summary content.",
                  },
                  form: "form",
                  llm_description: null,
                },
              ],
              labels: ["productivity"],
              output_schema: null,
            },
          ],
          labels: ["productivity"],
        },
        {
          id: "audio",
          author: "hjlarry",
          name: "audio",
          plugin_id: null,
          plugin_unique_identifier: "",
          description: {
            zh_Hans: "一个用于文本转语音和语音转文本的工具。",
            en_US: "A tool for tts and asr.",
            pt_BR: "A tool for tts and asr.",
            ja_JP: "A tool for tts and asr.",
          },
          icon: "http://127.0.0.1:5001/console/api/workspaces/current/tool-provider/builtin/audio/icon",
          label: {
            zh_Hans: "Audio",
            en_US: "Audio",
            pt_BR: "Audio",
            ja_JP: "Audio",
          },
          type: "builtin",
          team_credentials: {},
          is_team_authorization: true,
          allow_delete: false,
          tools: [
            {
              author: "hjlarry",
              name: "tts",
              label: {
                en_US: "Text To Speech",
                zh_Hans: "Text To Speech",
                pt_BR: "Text To Speech",
                ja_JP: "Text To Speech",
              },
              description: {
                en_US: "Convert text to audio file.",
                zh_Hans: "将文本转换为音频文件。",
                pt_BR: "Convert text to audio file.",
                ja_JP: "Convert text to audio file.",
              },
              parameters: [
                {
                  name: "text",
                  label: {
                    en_US: "Text",
                    zh_Hans: "文本",
                    pt_BR: "Text",
                    ja_JP: "Text",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: true,
                  default: null,
                  min: null,
                  max: null,
                  precision: null,
                  options: [],
                  type: "string",
                  human_description: {
                    en_US: "The text to be converted.",
                    zh_Hans: "要转换的文本。",
                    pt_BR: "The text to be converted.",
                    ja_JP: "The text to be converted.",
                  },
                  form: "llm",
                  llm_description: "The text to be converted.",
                },
                {
                  name: "model",
                  label: {
                    en_US: "Model",
                    zh_Hans: "Model",
                    pt_BR: "Model",
                    ja_JP: "Model",
                  },
                  placeholder: {
                    en_US: "Select a model",
                    zh_Hans: "选择模型",
                    pt_BR: "Select a model",
                    ja_JP: "Select a model",
                  },
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: true,
                  default: null,
                  min: null,
                  max: null,
                  precision: null,
                  options: [],
                  type: "select",
                  human_description: {
                    en_US: "All available TTS models. You can config model in the Model Provider of Settings.",
                    zh_Hans: "所有可用的 TTS 模型。你可以在设置中的模型供应商里配置。",
                    pt_BR: "All available TTS models. You can config model in the Model Provider of Settings.",
                    ja_JP: "All available TTS models. You can config model in the Model Provider of Settings.",
                  },
                  form: "form",
                  llm_description: null,
                },
              ],
              labels: ["utilities"],
              output_schema: null,
            },
            {
              author: "hjlarry",
              name: "asr",
              label: {
                en_US: "Speech To Text",
                zh_Hans: "Speech To Text",
                pt_BR: "Speech To Text",
                ja_JP: "Speech To Text",
              },
              description: {
                en_US: "Convert audio file to text.",
                zh_Hans: "将音频文件转换为文本。",
                pt_BR: "Convert audio file to text.",
                ja_JP: "Convert audio file to text.",
              },
              parameters: [
                {
                  name: "audio_file",
                  label: {
                    en_US: "Audio File",
                    zh_Hans: "音频文件",
                    pt_BR: "Audio File",
                    ja_JP: "Audio File",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: true,
                  default: null,
                  min: null,
                  max: null,
                  precision: null,
                  options: [],
                  type: "file",
                  human_description: {
                    en_US: "The audio file to be converted.",
                    zh_Hans: "要转换的音频文件。",
                    pt_BR: "The audio file to be converted.",
                    ja_JP: "The audio file to be converted.",
                  },
                  form: "llm",
                  llm_description: "The audio file to be converted.",
                },
                {
                  name: "model",
                  label: {
                    en_US: "Model",
                    zh_Hans: "Model",
                    pt_BR: "Model",
                    ja_JP: "Model",
                  },
                  placeholder: null,
                  scope: null,
                  auto_generate: null,
                  template: null,
                  required: true,
                  default: null,
                  min: null,
                  max: null,
                  precision: null,
                  options: [],
                  type: "select",
                  human_description: {
                    en_US: "All available ASR models. You can config model in the Model Provider of Settings.",
                    zh_Hans: "所有可用的 ASR 模型。你可以在设置中的模型供应商里配置。",
                    pt_BR: "All available ASR models. You can config model in the Model Provider of Settings.",
                    ja_JP: "All available ASR models. You can config model in the Model Provider of Settings.",
                  },
                  form: "form",
                  llm_description: null,
                },
              ],
              labels: ["utilities"],
              output_schema: null,
            },
          ],
          labels: ["utilities"],
        },
      ],
      customTools: [],
      workflowTools: [],
      toolPublished: false,
    },
    version: {
      draftUpdatedAt: 0,
      publishedAt: 0,
      currentVersion: null,
      isRestoring: false,
    },
    workflowDraft: {
      backupDraft: undefined,
      syncWorkflowDraftHash: "",
      isSyncingWorkflowDraft: false,
    },
    workflow: {
      appId: "b2ad53bf-a195-4d31-9738-ca76f87460a9",
      workflowRunningData: undefined,
      notInitialWorkflow: false,
      clipboardElements: [],
      selection: null,
      bundleNodeSize: null,
      controlMode: "hand",
      mousePosition: { pageX: 0, pageY: 0, elementX: 0, elementY: 0 },
      showConfirm: undefined,
      controlPromptEditorRerenderKey: 0,
      showImportDSLModal: false,
      showTips: "",
    },
    workflowEditor: {
      id: "fb6f7aa7-5886-4030-baee-ea0c50f26c23",
      graph: {
        nodes: [
          {
            data: {
              desc: "",
              selected: false,
              title: "start",
              type: "start",
              variables: [
                {
                  label: "title",
                  max_length: 100,
                  options: [],
                  required: true,
                  type: "text-input",
                  variable: "title",
                },
                {
                  label: "language",
                  max_length: 48,
                  options: ["中文", "English", "日本語"],
                  required: true,
                  type: "select",
                  variable: "language",
                },
              ],
            },
            height: 116,
            id: "1730257085761",
            position: {
              x: 30,
              y: 258,
            },
            positionAbsolute: {
              x: 30,
              y: 258,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom",
            width: 244,
          },
          {
            data: {
              context: {
                enabled: false,
                variable_selector: [],
              },
              desc: "",
              model: {
                completion_params: {
                  temperature: 1,
                },
                mode: "chat",
                name: "claude-3-5-sonnet-20241022",
                provider: "langgenius/anthropic/anthropic",
              },
              prompt_template: [
                {
                  id: "e18aef50-3449-4259-9559-c4d17101d533",
                  role: "system",
                  text: "<instruction>\n<task_description>\nGenerate a series of appropriate search engine queries to break down questions based on user inquiries\n</task_description>\n\n<examples>\n<example>\nInput: User asks how to learn programming\nOutput: 'programming learning methods, 'programming tutorials for beginners'\n</example>\n\n<example>\nInput: User wants to understand latest technology trends  \nOutput: 'tech trends 2021', 'latest technology news'\n</example>\n\n<example>\nInput: User seeks healthy eating advice\nOutput: 'healthy eating guide', 'balanced nutrition diet'\n</example>\n</examples>\n\n<instructions>\n1. Take user's question as input.\n2. Identify relevant keywords or phrases based on the topic of user's question.\n3. Use these keywords or phrases to make search engine queries.\n4. Generate a series of appropriate search engine queries to help break down user's question.\n5. Ensure output content does not contain any xml tags.\n6.The output must be pure and conform to the <example> style without other explanations.\n7.Break down into at least 4-6 subproblems.\n8.Output is separated only by commas.\n</instructions>",
                },
                {
                  id: "b0e446f2-b714-41e9-8eb6-292187a97796",
                  role: "user",
                  text: "title：{{#1730257085761.title#}}\nlanguage：{{#1730257085761.language#}}\nThe output must be pure and conform to the <example> style without other explanations.\nOutput is separated only by commas.\nBreak down into at least 4-6 subproblems.",
                },
              ],
              selected: false,
              title: "LLM",
              type: "llm",
              variables: [],
              vision: {
                enabled: false,
              },
            },
            height: 96,
            id: "1730257098742",
            position: {
              x: 334,
              y: 258,
            },
            positionAbsolute: {
              x: 334,
              y: 258,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom",
            width: 244,
          },
          {
            data: {
              code: "def main(input_str: str) -> dict:\n    if not input_str:\n        return {'result': []}\n    \n    input_str = input_str.strip().strip('\"')\n    items = [item.strip() for item in input_str.split(',')]\n    \n    return {'result': items}",
              code_language: "python3",
              desc: "",
              outputs: {
                result: {
                  children: null,
                  type: "array[string]",
                },
              },
              selected: false,
              title: "code",
              type: "code",
              variables: [
                {
                  value_selector: ["1730257098742", "text"],
                  variable: "input_str",
                },
              ],
            },
            height: 54,
            id: "1730257648212",
            position: {
              x: 638,
              y: 258,
            },
            positionAbsolute: {
              x: 638,
              y: 258,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom",
            width: 244,
          },
          {
            data: {
              desc: "",
              error_handle_mode: "continue-on-error",
              height: 333,
              is_parallel: true,
              iterator_selector: ["1730257648212", "result"],
              output_selector: ["1730259235391", "text"],
              output_type: "array[string]",
              parallel_nums: 10,
              selected: false,
              start_node_id: "1730257830072start",
              title: "interaction",
              type: "iteration",
              width: 913,
            },
            height: 333,
            id: "1730257830072",
            position: {
              x: 942,
              y: 394,
            },
            positionAbsolute: {
              x: 942,
              y: 394,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom",
            width: 913,
            zIndex: 1,
          },
          {
            data: {
              desc: "",
              isInIteration: true,
              selected: false,
              title: "",
              type: "iteration-start",
            },
            draggable: false,
            height: 48,
            id: "1730257830072start",
            parentId: "1730257830072",
            position: {
              x: 24,
              y: 68,
            },
            positionAbsolute: {
              x: 966,
              y: 462,
            },
            selectable: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom-iteration-start",
            width: 44,
            zIndex: 1002,
          },
          {
            data: {
              desc: "",
              isInIteration: true,
              iteration_id: "1730257830072",
              provider_id: "tavily",
              provider_name: "tavily",
              provider_type: "builtin",
              selected: false,
              title: "TavilySearch",
              tool_configurations: {
                exclude_domains: null,
                include_answer: null,
                include_domains: null,
                include_images: null,
                include_raw_content: null,
                max_results: 5,
                search_depth: "basic",
              },
              tool_label: "TavilySearch",
              tool_name: "tavily_search",
              tool_parameters: {
                query: {
                  type: "mixed",
                  value: "{{#1730257830072.item#}}",
                },
              },
              type: "tool",
            },
            height: 246,
            id: "1730257879652",
            parentId: "1730257830072",
            position: {
              x: 128,
              y: 67,
            },
            positionAbsolute: {
              x: 1070,
              y: 461,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom",
            width: 244,
            zIndex: 1002,
          },
          {
            data: {
              context: {
                enabled: false,
                variable_selector: [],
              },
              desc: "",
              isInIteration: true,
              iteration_id: "1730257830072",
              model: {
                completion_params: {
                  temperature: 0.7,
                },
                mode: "chat",
                name: "claude-3-haiku-20240307",
                provider: "langgenius/anthropic/anthropic",
              },
              prompt_template: [
                {
                  edition_type: "basic",
                  id: "d8e18834-ba12-4acb-b376-15340d30a3e3",
                  jinja2_text:
                    '"{research_summary}" Using the above information, answer the following question or topic: "{question}" in a detailed report — The report should focus on the answer to the question, should be well structured, informative, in depth, with facts and numbers if available, a minimum of 1,200 words and with markdown syntax and apa format. Write all source urls at the end of the report in apa format. You should write your report only based on the given information and nothing else.',
                  role: "system",
                  text: "Your goal is to provide answers based on information from the internet. \nYou must use the provided Tavily search API function to find relevant online information. \nYou should never use your own knowledge to answer questions.\nPlease include relevant url sources in the end of your answers",
                },
                {
                  id: "b23ba544-1b25-4d0a-abdf-34a6c22a2c76",
                  role: "user",
                  text: 'language：{{#1730257085761.language#}}\n "{{#1730257879652.text#}}" Using the above information, answer the following question or topic: "{{#1730257830072.item#}} "\n',
                },
              ],
              selected: false,
              title: "LLM 3",
              type: "llm",
              variables: [],
              vision: {
                enabled: false,
              },
            },
            height: 96,
            id: "1730259235391",
            parentId: "1730257830072",
            position: {
              x: 416.1699410031715,
              y: 71.98653004766629,
            },
            positionAbsolute: {
              x: 1358.1699410031715,
              y: 465.9865300476663,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom",
            width: 244,
            zIndex: 1002,
          },
          {
            data: {
              context: {
                enabled: false,
                variable_selector: [],
              },
              desc: "",
              model: {
                completion_params: {
                  temperature: 0.7,
                },
                mode: "chat",
                name: "gpt-4o",
                provider: "langgenius/openai/openai",
              },
              prompt_template: [
                {
                  id: "3b248cc7-ce1c-4d24-b20c-aa988aaad672",
                  role: "system",
                  text: "according{{#1730257648212.result#}}，{{#1730257085761.title#}}Generate 3 to 5 sub-titles.\n<instructions>\nPlease generate 4 subheadings for the main title following these steps:\nCarefully read the provided main title and related content\nAnalyze the core theme and key information points of the main title\nEnsure the generated subheadings maintain consistency and relevance with the main title\nEach subheading should:\nBe concise and appropriate in length\nHighlight a unique angle or key point\nCapture readers' interest\nMatch the overall style and tone of the article\nBetween subheadings:\nContent should not overlap\nLogical order should be maintained\nShould collectively support the main title\nUse numerical sequence (1, 2, 3...) to mark each subheading\nOutputformatrequirements:\nEach subheading on a separate line\nNo XML tags included\nOutput subheadings content only\n</instructions>",
                },
                {
                  id: "5a7b9e7a-e8f8-4564-a9bf-85861c4fe312",
                  role: "user",
                  text: "language：{{#1730257085761.language#}}\nGenerate a series of appropriate sub-title to help break down {{#1730257085761.title#}}.\nBreaks down complex topics into manageable subtopics",
                },
              ],
              selected: false,
              title: "LLM 3",
              type: "llm",
              variables: [],
              vision: {
                enabled: false,
              },
            },
            height: 96,
            id: "1730259707121",
            position: {
              x: 1276.5,
              y: 258,
            },
            positionAbsolute: {
              x: 1276.5,
              y: 258,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom",
            width: 244,
          },
          {
            data: {
              desc: "",
              selected: false,
              template:
                "<h1>{{ arg0 }}</h1>\n\n<h2>{{ arg1 }}</h2>\n<div>{{ arg5 }}</div>\n\n<h2>{{ arg2 }}</h2>\n<div>{{ arg6 }}</div>\n\n<h2>{{ arg3 }}</h2>\n<div>{{ arg7 }}</div>\n\n<h2>{{ arg4 }}</h2>\n<div>{{ arg8 }}</div>",
              title: "Template conversion",
              type: "template-transform",
              variables: [
                {
                  value_selector: ["1730257085761", "title"],
                  variable: "arg0",
                },
                {
                  value_selector: ["1730260137415", "sub_title1"],
                  variable: "arg1",
                },
                {
                  value_selector: ["1730260137415", "sub_title2"],
                  variable: "arg2",
                },
                {
                  value_selector: ["1730260137415", "sub_title3"],
                  variable: "arg3",
                },
                {
                  value_selector: ["1730260137415", "sub_title4"],
                  variable: "arg4",
                },
                {
                  value_selector: ["1730260569281", "text"],
                  variable: "arg5",
                },
                {
                  value_selector: ["1730260824960", "text"],
                  variable: "arg6",
                },
                {
                  value_selector: ["17302609631470", "text"],
                  variable: "arg7",
                },
                {
                  value_selector: ["17302610163900", "text"],
                  variable: "arg8",
                },
              ],
            },
            height: 54,
            id: "1730259990083",
            position: {
              x: 2523,
              y: 394,
            },
            positionAbsolute: {
              x: 2523,
              y: 394,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom",
            width: 244,
          },
          {
            data: {
              desc: "",
              instruction:
                "{{#1730259707121.text#}}Extract the return value in the output value as four independent parameters.Avoids redundancy by tracking previously written content",
              model: {
                completion_params: {
                  temperature: 0.7,
                },
                mode: "chat",
                name: "claude-3-5-sonnet-20241022",
                provider: "langgenius/anthropic/anthropic",
              },
              parameters: [
                {
                  description: "NO.1 sub title",
                  name: "sub_title1",
                  required: false,
                  type: "string",
                },
                {
                  description: "NO.2 sub_title",
                  name: "sub_title2",
                  required: false,
                  type: "string",
                },
                {
                  description: "NO.3 sub_title",
                  name: "sub_title3",
                  required: false,
                  type: "string",
                },
                {
                  description: "NO.4 sub_title",
                  name: "sub_title4",
                  required: false,
                  type: "string",
                },
              ],
              query: ["1730259707121", "text"],
              reasoning_mode: "prompt",
              selected: false,
              title: "Parameter extractor",
              type: "parameter-extractor",
              variables: [],
              vision: {
                enabled: false,
              },
            },
            height: 96,
            id: "1730260137415",
            position: {
              x: 1915,
              y: 258,
            },
            positionAbsolute: {
              x: 1915,
              y: 258,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom",
            width: 244,
          },
          {
            data: {
              context: {
                enabled: false,
                variable_selector: [],
              },
              desc: "",
              model: {
                completion_params: {
                  temperature: 1,
                },
                mode: "chat",
                name: "claude-3-haiku-20240307",
                provider: "langgenius/anthropic/anthropic",
              },
              prompt_template: [
                {
                  id: "3ef1efde-48b7-4f8d-830b-44e92815950f",
                  role: "system",
                  text: "in a detailed report — The report should focus on the answer to {{#1730260137415.sub_title1#}}and nothing else.",
                },
                {
                  id: "04881f0e-1a81-4c5c-813a-5123d62689e8",
                  role: "user",
                  text: "language：{{#1730257085761.language#}}\ncontext：{{#1730257830072.output#}}\nProvide the research report in the specified language, avoiding small talk.\n\n\n",
                },
              ],
              selected: false,
              title: "LLM 5",
              type: "llm",
              variables: [],
              vision: {
                enabled: false,
              },
            },
            height: 96,
            id: "1730260569281",
            position: {
              x: 2219,
              y: 258,
            },
            positionAbsolute: {
              x: 2219,
              y: 258,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom",
            width: 244,
          },
          {
            data: {
              context: {
                enabled: false,
                variable_selector: [],
              },
              desc: "",
              model: {
                completion_params: {
                  temperature: 1,
                },
                mode: "chat",
                name: "claude-3-haiku-20240307",
                provider: "langgenius/anthropic/anthropic",
              },
              prompt_template: [
                {
                  id: "c059b7a1-a7cb-4d2d-a258-cc4bd122ff7f",
                  role: "system",
                  text: "in a detailed report — The report should focus on the answer to {{#1730260137415.sub_title2#}}and nothing else.",
                },
                {
                  id: "e494e57c-eff3-434d-bba7-4981a6dfd212",
                  role: "user",
                  text: "language：{{#1730257085761.language#}}\ncontext：{{#1730257830072.output#}}\nProvide the research report in the specified language, avoiding small talk.\n\n\n",
                },
              ],
              selected: false,
              title: "LLM 6",
              type: "llm",
              variables: [],
              vision: {
                enabled: false,
              },
            },
            height: 96,
            id: "1730260824960",
            position: {
              x: 2219,
              y: 394,
            },
            positionAbsolute: {
              x: 2219,
              y: 394,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom",
            width: 244,
          },
          {
            data: {
              context: {
                enabled: false,
                variable_selector: [],
              },
              desc: "",
              model: {
                completion_params: {
                  temperature: 1,
                },
                mode: "chat",
                name: "claude-3-haiku-20240307",
                provider: "langgenius/anthropic/anthropic",
              },
              prompt_template: [
                {
                  id: "c059b7a1-a7cb-4d2d-a258-cc4bd122ff7f",
                  role: "system",
                  text: "in a detailed report — The report should focus on the answer to {{#1730260137415.sub_title3#}}and nothing else.",
                },
                {
                  id: "53cd6741-f1ef-4480-9778-9e8c1ea2e298",
                  role: "user",
                  text: "language：{{#1730257085761.language#}}\ncontext：{{#1730257830072.output#}}\nProvide the research report in the specified language, avoiding small talk.\n\n",
                },
              ],
              selected: false,
              title: "LLM 7",
              type: "llm",
              variables: [],
              vision: {
                enabled: false,
              },
            },
            height: 96,
            id: "17302609631470",
            position: {
              x: 2219,
              y: 530,
            },
            positionAbsolute: {
              x: 2219,
              y: 530,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom",
            width: 244,
          },
          {
            data: {
              context: {
                enabled: false,
                variable_selector: [],
              },
              desc: "",
              model: {
                completion_params: {
                  temperature: 1,
                },
                mode: "chat",
                name: "claude-3-haiku-20240307",
                provider: "langgenius/anthropic/anthropic",
              },
              prompt_template: [
                {
                  id: "c059b7a1-a7cb-4d2d-a258-cc4bd122ff7f",
                  role: "system",
                  text: "in a detailed report — The report should focus on the answer to {{#1730260137415.sub_title4#}}and nothing else.",
                },
                {
                  id: "2773ef9d-37b8-49f8-9455-c2399538407f",
                  role: "user",
                  text: "language：{{#1730257085761.language#}}\ncontext：{{#1730257830072.output#}}\nProvide the research report in the specified language, avoiding small talk.\n\n\n\n",
                },
              ],
              selected: false,
              title: "LLM 8",
              type: "llm",
              variables: [],
              vision: {
                enabled: false,
              },
            },
            height: 96,
            id: "17302610163900",
            position: {
              x: 2219,
              y: 666,
            },
            positionAbsolute: {
              x: 2219,
              y: 666,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom",
            width: 244,
          },
          {
            data: {
              desc: "",
              outputs: [
                {
                  value_selector: ["1730259990083", "output"],
                  variable: "output",
                },
              ],
              selected: false,
              title: "End",
              type: "end",
            },
            height: 90,
            id: "1730261407654",
            position: {
              x: 2827,
              y: 394,
            },
            positionAbsolute: {
              x: 2827,
              y: 394,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom",
            width: 244,
          },
          {
            data: {
              author: "Dify",
              desc: "",
              height: 168,
              selected: false,
              showAuthor: true,
              text: '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"GPT-Rasearcher receives two variable inputs. 1. title: the proposition to be studied. 2. language: language preference for the research report.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
              theme: "blue",
              title: "",
              type: "",
              width: 240,
            },
            height: 168,
            id: "1730387967784",
            position: {
              x: 28.05097515220939,
              y: 7.975706889733289,
            },
            positionAbsolute: {
              x: 28.05097515220939,
              y: 7.975706889733289,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom-note",
            width: 240,
          },
          {
            data: {
              author: "Dify",
              desc: "",
              height: 173,
              selected: false,
              showAuthor: true,
              text: '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Step1: First, let the LLM provide a series of search engine queries related to the proposition. Comprehensive research can be conducted through queries from different perspectives.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
              theme: "blue",
              title: "",
              type: "",
              width: 242,
            },
            height: 173,
            id: "1730388614165",
            position: {
              x: 321.6365008011338,
              y: 7.975706889733289,
            },
            positionAbsolute: {
              x: 321.6365008011338,
              y: 7.975706889733289,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom-note",
            width: 242,
          },
          {
            data: {
              author: "Dify",
              desc: "",
              height: 188,
              selected: false,
              showAuthor: true,
              text: '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Step2: Since the input requirement for iteration is an array, we use a code node to extract subqueries from the string output by the LLM. Here, the new function \\"code generator\\" can be used to quickly generate the required code.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
              theme: "blue",
              title: "",
              type: "",
              width: 240,
            },
            height: 188,
            id: "1730388689290",
            position: {
              x: 635.9314896948702,
              y: 7.975706889733289,
            },
            positionAbsolute: {
              x: 635.9314896948702,
              y: 7.975706889733289,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom-note",
            width: 240,
          },
          {
            data: {
              author: "Dify",
              desc: "",
              height: 224,
              selected: false,
              showAuthor: true,
              text: '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Step3: We constructed two parallel branches. One is to use the LLM to summarize secondary headings suitable for proposition research based on search engine queries. The other branch uses iteration and simultaneously queries each subquery with Tavily and then conducts inductive research using the LLM. Here, we use the advanced functions of iteration and the parallel mode to accelerate the search.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
              theme: "blue",
              title: " (1)",
              type: "",
              width: 281,
            },
            height: 224,
            id: "17303887996700",
            position: {
              x: 968.506506560585,
              y: 7.975706889733289,
            },
            positionAbsolute: {
              x: 968.506506560585,
              y: 7.975706889733289,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom-note",
            width: 281,
          },
          {
            data: {
              author: "Dify",
              desc: "",
              height: 198,
              selected: false,
              showAuthor: true,
              text: '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Step 4: We use a parameter extractor to extract a total of four sub-titles of the secondary research propositions output by the previous LLM. Then, we use four parallel branches to take the iterative output as the context (now the prompt can support injecting an array [string]) to answer the four questions.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
              theme: "blue",
              title: "  (2)",
              type: "",
              width: 289,
            },
            height: 198,
            id: "17303896484860",
            position: {
              x: 1279.1060058303985,
              y: 7.975706889733289,
            },
            positionAbsolute: {
              x: 1279.1060058303985,
              y: 7.975706889733289,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom-note",
            width: 289,
          },
          {
            data: {
              author: "Dify",
              desc: "",
              height: 156,
              selected: false,
              showAuthor: true,
              text: '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Finally, we use template nodes to orderly splice the previous first-level headings, second-level headings, and research conclusions to obtain a complete research report. 😃","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
              theme: "blue",
              title: "  (3)",
              type: "",
              width: 283,
            },
            height: 156,
            id: "17303898217580",
            position: {
              x: 1676.1759535081464,
              y: 7.975706889733289,
            },
            positionAbsolute: {
              x: 1676.1759535081464,
              y: 7.975706889733289,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom-note",
            width: 283,
          },
          {
            data: {
              author: "Dify",
              desc: "",
              height: 175,
              selected: false,
              showAuthor: true,
              text: '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"example title：","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"1.A Study of Florence Art History","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"2.The Complete History of Minecraft","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"3.The Chronicles of OpenAI","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0},{"children":[{"type":"linebreak","version":1}],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
              theme: "blue",
              title: "",
              type: "",
              width: 240,
            },
            height: 175,
            id: "1730452566694",
            position: {
              x: -241.22286003072247,
              y: 6.623354710724881,
            },
            positionAbsolute: {
              x: -241.22286003072247,
              y: 6.623354710724881,
            },
            selected: false,
            sourcePosition: "right",
            targetPosition: "left",
            type: "custom-note",
            width: 240,
          },
          {
            id: "1743984382525",
            type: "custom",
            data: {
              type: "http-request",
              title: "HTTP Request",
              desc: "",
              variables: [],
              method: "get",
              url: "",
              authorization: {
                type: "no-auth",
                config: null,
              },
              headers: "",
              params: "",
              body: {
                type: "none",
                data: [],
              },
              timeout: {
                max_connect_timeout: 0,
                max_read_timeout: 0,
                max_write_timeout: 0,
              },
              retry_config: {
                retry_enabled: true,
                max_retries: 3,
                retry_interval: 100,
              },
              selected: false,
            },
            position: {
              x: 30,
              y: 414,
            },
            targetPosition: "left",
            sourcePosition: "right",
            positionAbsolute: {
              x: 30,
              y: 414,
            },
            width: 244,
            height: 80,
            selected: false,
          },
          {
            id: "1744144982768",
            type: "custom-note",
            data: {
              title: "",
              desc: "",
              type: "",
              text: "",
              theme: "blue",
              author: "Dify",
              showAuthor: true,
              width: 240,
              height: 88,
              selected: false,
            },
            position: {
              x: 31.029301352524314,
              y: 544.7132431807495,
            },
            targetPosition: "left",
            sourcePosition: "right",
            positionAbsolute: {
              x: 31.029301352524314,
              y: 544.7132431807495,
            },
            width: 240,
            height: 88,
            selected: true,
          },
        ],
        edges: [
          {
            data: {
              isInIteration: false,
              sourceType: "start",
              targetType: "llm",
            },
            id: "1730257085761-source-1730257098742-target",
            selected: false,
            source: "1730257085761",
            sourceHandle: "source",
            target: "1730257098742",
            targetHandle: "target",
            type: "custom",
            zIndex: 0,
          },
          {
            data: {
              isInIteration: false,
              sourceType: "llm",
              targetType: "code",
            },
            id: "1730257098742-source-1730257648212-target",
            selected: false,
            source: "1730257098742",
            sourceHandle: "source",
            target: "1730257648212",
            targetHandle: "target",
            type: "custom",
            zIndex: 0,
          },
          {
            data: {
              isInIteration: false,
              sourceType: "code",
              targetType: "iteration",
            },
            id: "1730257648212-source-1730257830072-target",
            selected: false,
            source: "1730257648212",
            sourceHandle: "source",
            target: "1730257830072",
            targetHandle: "target",
            type: "custom",
            zIndex: 0,
          },
          {
            data: {
              isInIteration: true,
              iteration_id: "1730257830072",
              sourceType: "iteration-start",
              targetType: "tool",
            },
            id: "1730257830072start-source-1730257879652-target",
            selected: false,
            source: "1730257830072start",
            sourceHandle: "source",
            target: "1730257879652",
            targetHandle: "target",
            type: "custom",
            zIndex: 1002,
          },
          {
            data: {
              isInIteration: true,
              iteration_id: "1730257830072",
              sourceType: "tool",
              targetType: "llm",
            },
            id: "1730257879652-source-1730259235391-target",
            selected: false,
            source: "1730257879652",
            sourceHandle: "source",
            target: "1730259235391",
            targetHandle: "target",
            type: "custom",
            zIndex: 1002,
          },
          {
            data: {
              isInIteration: false,
              sourceType: "code",
              targetType: "llm",
            },
            id: "1730257648212-source-1730259707121-target",
            selected: false,
            source: "1730257648212",
            sourceHandle: "source",
            target: "1730259707121",
            targetHandle: "target",
            type: "custom",
            zIndex: 0,
          },
          {
            data: {
              isInIteration: false,
              sourceType: "llm",
              targetType: "parameter-extractor",
            },
            id: "1730259707121-source-1730260137415-target",
            selected: false,
            source: "1730259707121",
            sourceHandle: "source",
            target: "1730260137415",
            targetHandle: "target",
            type: "custom",
            zIndex: 0,
          },
          {
            data: {
              isInIteration: false,
              sourceType: "llm",
              targetType: "template-transform",
            },
            id: "1730260569281-source-1730259990083-target",
            selected: false,
            source: "1730260569281",
            sourceHandle: "source",
            target: "1730259990083",
            targetHandle: "target",
            type: "custom",
            zIndex: 0,
          },
          {
            data: {
              isInIteration: false,
              sourceType: "parameter-extractor",
              targetType: "llm",
            },
            id: "1730260137415-source-1730260569281-target",
            selected: false,
            source: "1730260137415",
            sourceHandle: "source",
            target: "1730260569281",
            targetHandle: "target",
            type: "custom",
            zIndex: 0,
          },
          {
            data: {
              isInIteration: false,
              sourceType: "parameter-extractor",
              targetType: "llm",
            },
            id: "1730260137415-source-1730260824960-target",
            selected: false,
            source: "1730260137415",
            sourceHandle: "source",
            target: "1730260824960",
            targetHandle: "target",
            type: "custom",
            zIndex: 0,
          },
          {
            data: {
              isInIteration: false,
              sourceType: "iteration",
              targetType: "parameter-extractor",
            },
            id: "1730257830072-source-1730260137415-target",
            selected: false,
            source: "1730257830072",
            sourceHandle: "source",
            target: "1730260137415",
            targetHandle: "target",
            type: "custom",
            zIndex: 0,
          },
          {
            data: {
              isInIteration: false,
              sourceType: "parameter-extractor",
              targetType: "llm",
            },
            id: "1730260137415-source-17302609631470-target",
            selected: false,
            source: "1730260137415",
            sourceHandle: "source",
            target: "17302609631470",
            targetHandle: "target",
            type: "custom",
            zIndex: 0,
          },
          {
            data: {
              isInIteration: false,
              sourceType: "parameter-extractor",
              targetType: "llm",
            },
            id: "1730260137415-source-17302610163900-target",
            selected: false,
            source: "1730260137415",
            sourceHandle: "source",
            target: "17302610163900",
            targetHandle: "target",
            type: "custom",
            zIndex: 0,
          },
          {
            data: {
              isInIteration: false,
              sourceType: "llm",
              targetType: "template-transform",
            },
            id: "1730260824960-source-1730259990083-target",
            selected: false,
            source: "1730260824960",
            sourceHandle: "source",
            target: "1730259990083",
            targetHandle: "target",
            type: "custom",
            zIndex: 0,
          },
          {
            data: {
              isInIteration: false,
              sourceType: "llm",
              targetType: "template-transform",
            },
            id: "17302609631470-source-1730259990083-target",
            selected: false,
            source: "17302609631470",
            sourceHandle: "source",
            target: "1730259990083",
            targetHandle: "target",
            type: "custom",
            zIndex: 0,
          },
          {
            data: {
              isInIteration: false,
              sourceType: "llm",
              targetType: "template-transform",
            },
            id: "17302610163900-source-1730259990083-target",
            selected: false,
            source: "17302610163900",
            sourceHandle: "source",
            target: "1730259990083",
            targetHandle: "target",
            type: "custom",
            zIndex: 0,
          },
          {
            data: {
              isInIteration: false,
              sourceType: "template-transform",
              targetType: "end",
            },
            id: "1730259990083-source-1730261407654-target",
            selected: false,
            source: "1730259990083",
            sourceHandle: "source",
            target: "1730261407654",
            targetHandle: "target",
            type: "custom",
            zIndex: 0,
          },
        ],
        viewport: {
          x: -82,
          y: 191,
          zoom: 0.7,
        },
      },
      features: {
        opening_statement: "",
        suggested_questions: [],
        suggested_questions_after_answer: {
          enabled: false,
        },
        text_to_speech: {
          enabled: false,
          language: "",
          voice: "",
        },
        speech_to_text: {
          enabled: false,
        },
        retriever_resource: {
          enabled: true,
        },
        sensitive_word_avoidance: {
          enabled: false,
        },
        file_upload: {
          image: {
            enabled: false,
            number_limits: 3,
            transfer_methods: ["local_file", "remote_url"],
          },
          enabled: false,
          allowed_file_types: ["image"],
          allowed_file_extensions: [".JPG", ".JPEG", ".PNG", ".GIF", ".WEBP", ".SVG"],
          allowed_file_upload_methods: ["local_file", "remote_url"],
          number_limits: 3,
          fileUploadConfig: {
            file_size_limit: 15,
            batch_count_limit: 5,
            image_file_size_limit: 10,
            video_file_size_limit: 100,
            audio_file_size_limit: 50,
            workflow_file_upload_limit: 10,
          },
        },
      },
      hash: "0d0d783351982ec0031f472fb9ebdd7873a26457bfe4c4c7f0566590a9312a4d",
      version: "draft",
      marked_name: "",
      marked_comment: "",
      created_by: {
        id: "ea3db04e-2aec-4c18-a196-6fbb56ffd2a9",
        name: "Dify",
        email: "peterjaberau@gmail.com",
      },
      created_at: 1743984090,
      updated_by: {
        id: "ea3db04e-2aec-4c18-a196-6fbb56ffd2a9",
        name: "Dify",
        email: "peterjaberau@gmail.com",
      },
      updated_at: 1744190153,
      tool_published: false,
      environment_variables: [
        {
          id: "8db67049-1c7e-449a-8db2-85e8b9dcc606",
          name: "varStr",
          value: "string vaule 1",
          value_type: "string",
        },
      ],
      conversation_variables: [],
    },
  },
  states: {
    idle: {
      on: {
        FORM_INPUTS_CHANGED: {
          actions: ["setInputs"],
        },
        FORM_FILES_CHANGED: {
          actions: ["setFiles"],
        },
        TOGGLE_CHANGED: {
          actions: ["setToggle"],
        },
      },
    },
  },
});
