export const capture = {
  initialData: {
    customer: {
      id: 'cus_01JQDTPXX68AHZFH610641WZM2',
      company_name: null,
      first_name: 'Peter',
      last_name: 'Demo1',
      email: 'peter@gmail.com',
      phone: '0414949323',
      metadata: null,
      has_account: true,
      created_by: null,
      created_at: '2025-03-28T07:33:22.471Z',
      updated_at: '2025-03-28T07:33:22.471Z',
      deleted_at: null,
      addresses: [
        {
          id: 'cuaddr_01JQDTR2S3VJ2QSD31CH59A9HX',
          address_name: null,
          is_default_shipping: true,
          is_default_billing: false,
          company: '',
          first_name: 'Peter',
          last_name: 'Demo1',
          address_1: '41 Chuter Avenue',
          address_2: '',
          city: 'Sydney',
          country_code: 'gb',
          province: 'NSW',
          postal_code: '2217',
          phone: '0414949323',
          metadata: null,
          customer_id: 'cus_01JQDTPXX68AHZFH610641WZM2',
          created_at: '2025-03-28T07:34:00.228Z',
          updated_at: '2025-03-28T07:34:00.228Z',
          deleted_at: null,
        },
        {
          id: 'cuaddr_01JQHWT6ET81NSNR2M6599QWZA',
          address_name: 'Sydney',
          is_default_shipping: false,
          is_default_billing: false,
          company: '',
          first_name: null,
          last_name: null,
          address_1: 'Montery Street',
          address_2: '',
          city: '',
          country_code: 'au',
          province: '',
          postal_code: '',
          phone: '',
          metadata: null,
          customer_id: 'cus_01JQDTPXX68AHZFH610641WZM2',
          created_at: '2025-03-29T21:27:04.410Z',
          updated_at: '2025-03-29T21:27:04.410Z',
          deleted_at: null,
        },
      ],
    },
  },
  customer: {
    id: 'cus_01JQDTPXX68AHZFH610641WZM2',
    company_name: null,
    first_name: 'Peter',
    last_name: 'Demo1',
    email: 'peter@gmail.com',
    phone: '0414949323',
    metadata: null,
    has_account: true,
    created_by: null,
    created_at: '2025-03-28T07:33:22.471Z',
    updated_at: '2025-03-28T07:33:22.471Z',
    deleted_at: null,
    addresses: [
      {
        id: 'cuaddr_01JQDTR2S3VJ2QSD31CH59A9HX',
        address_name: null,
        is_default_shipping: true,
        is_default_billing: false,
        company: '',
        first_name: 'Peter',
        last_name: 'Demo1',
        address_1: '41 Chuter Avenue',
        address_2: '',
        city: 'Sydney',
        country_code: 'gb',
        province: 'NSW',
        postal_code: '2217',
        phone: '0414949323',
        metadata: null,
        customer_id: 'cus_01JQDTPXX68AHZFH610641WZM2',
        created_at: '2025-03-28T07:34:00.228Z',
        updated_at: '2025-03-28T07:34:00.228Z',
        deleted_at: null,
      },
      {
        id: 'cuaddr_01JQHWT6ET81NSNR2M6599QWZA',
        address_name: 'Sydney',
        is_default_shipping: false,
        is_default_billing: false,
        company: '',
        first_name: null,
        last_name: null,
        address_1: 'Montery Street',
        address_2: '',
        city: '',
        country_code: 'au',
        province: '',
        postal_code: '',
        phone: '',
        metadata: null,
        customer_id: 'cus_01JQDTPXX68AHZFH610641WZM2',
        created_at: '2025-03-29T21:27:04.410Z',
        updated_at: '2025-03-29T21:27:04.410Z',
        deleted_at: null,
      },
    ],
  },
  getWidgets: {
    after: [],
    before: [],
    sideAfter: [],
    sideBefore: [],
  },
};

export const captureCustomerOrders = {
  useOrderTableQueryAll: {
    searchParams: {
      limit: 10,
      offset: 0,
      order: '-display_id',
    },
    raw: {},
  },
  useOrdersAll: {
    orders: [
      {
        id: 'order_01JQDV93AEHJ6VNSCE13EWYTB1',
        status: 'pending',
        display_id: 1,
        created_at: '2025-03-28T07:43:17.839Z',
        email: 'peter@gmail.com',
        total: 30,
        currency_code: 'eur',
        version: 2,
        customer_id: 'cus_01JQDTPXX68AHZFH610641WZM2',
        sales_channel_id: 'sc_01JQDTGY0BDTYDQN9FZYKMD5Q1',
        items: [
          {
            id: 'ordli_01JQDV93AERP766VZB13PXHXYE',
            title: 'XL',
            subtitle: 'Medusa Shorts',
            thumbnail: 'https://medusa-public-images.s3.eu-west-1.amazonaws.com/shorts-vintage-front.png',
            variant_id: 'variant_01JQDTH05M2QKQ3T0HCF691XWR',
            product_id: 'prod_01JQDTH04AMRGFM5GRE9DVT7XQ',
            product_title: 'Medusa Shorts',
            product_description:
              'Reimagine the feeling of classic shorts. With our cotton shorts, everyday essentials no longer have to be ordinary.',
            product_subtitle: null,
            product_type: null,
            product_type_id: null,
            product_collection: null,
            product_handle: 'shorts',
            variant_sku: 'SHORTS-XL',
            variant_barcode: null,
            variant_title: 'XL',
            variant_option_values: null,
            requires_shipping: true,
            is_discountable: true,
            is_tax_inclusive: false,
            is_custom_price: false,
            metadata: {},
            raw_compare_at_unit_price: null,
            raw_unit_price: {
              value: '10',
              precision: 20,
            },
            created_at: '2025-03-28T07:43:17.840Z',
            updated_at: '2025-03-28T07:43:17.840Z',
            deleted_at: null,
            tax_lines: [],
            adjustments: [],
            compare_at_unit_price: null,
            unit_price: 10,
            quantity: 1,
            raw_quantity: {
              value: '1',
              precision: 20,
            },
            detail: {
              id: 'orditem_01JQE2P1F98JPTQ14JJQWTTZAS',
              version: 2,
              metadata: null,
              order_id: 'order_01JQDV93AEHJ6VNSCE13EWYTB1',
              raw_unit_price: {
                value: '10',
                precision: 20,
              },
              raw_compare_at_unit_price: null,
              raw_quantity: {
                value: '1',
                precision: 20,
              },
              raw_fulfilled_quantity: {
                value: '1',
                precision: 20,
              },
              raw_delivered_quantity: {
                value: '0',
                precision: 20,
              },
              raw_shipped_quantity: {
                value: '0',
                precision: 20,
              },
              raw_return_requested_quantity: {
                value: '0',
                precision: 20,
              },
              raw_return_received_quantity: {
                value: '0',
                precision: 20,
              },
              raw_return_dismissed_quantity: {
                value: '0',
                precision: 20,
              },
              raw_written_off_quantity: {
                value: '0',
                precision: 20,
              },
              created_at: '2025-03-28T09:52:41.968Z',
              updated_at: '2025-03-28T09:52:41.968Z',
              deleted_at: null,
              item_id: 'ordli_01JQDV93AERP766VZB13PXHXYE',
              unit_price: 10,
              compare_at_unit_price: null,
              quantity: 1,
              fulfilled_quantity: 1,
              delivered_quantity: 0,
              shipped_quantity: 0,
              return_requested_quantity: 0,
              return_received_quantity: 0,
              return_dismissed_quantity: 0,
              written_off_quantity: 0,
            },
            subtotal: 10,
            total: 10,
            original_total: 10,
            discount_total: 0,
            discount_subtotal: 0,
            discount_tax_total: 0,
            tax_total: 0,
            original_tax_total: 0,
            refundable_total_per_unit: 10,
            refundable_total: 10,
            fulfilled_total: 10,
            shipped_total: 0,
            return_requested_total: 0,
            return_received_total: 0,
            return_dismissed_total: 0,
            write_off_total: 0,
            raw_subtotal: {
              value: '10',
              precision: 20,
            },
            raw_total: {
              value: '10',
              precision: 20,
            },
            raw_original_total: {
              value: '10',
              precision: 20,
            },
            raw_discount_total: {
              value: '0',
              precision: 20,
            },
            raw_discount_subtotal: {
              value: '0',
              precision: 20,
            },
            raw_discount_tax_total: {
              value: '0',
              precision: 20,
            },
            raw_tax_total: {
              value: '0',
              precision: 20,
            },
            raw_original_tax_total: {
              value: '0',
              precision: 20,
            },
            raw_refundable_total_per_unit: {
              value: '10',
              precision: 20,
            },
            raw_refundable_total: {
              value: '10',
              precision: 20,
            },
            raw_fulfilled_total: {
              value: '10',
              precision: 20,
            },
            raw_shipped_total: {
              value: '0',
              precision: 20,
            },
            raw_return_requested_total: {
              value: '0',
              precision: 20,
            },
            raw_return_received_total: {
              value: '0',
              precision: 20,
            },
            raw_return_dismissed_total: {
              value: '0',
              precision: 20,
            },
            raw_write_off_total: {
              value: '0',
              precision: 20,
            },
          },
          {
            id: 'ordli_01JQDV93AEZSQSXHMHEMQWTG5G',
            title: 'M',
            subtitle: 'Medusa Sweatshirt',
            thumbnail: 'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatshirt-vintage-front.png',
            variant_id: 'variant_01JQDTH05M2Y7WAD82ERNY3R90',
            product_id: 'prod_01JQDTH04AZVTP47HQHM0Z83RG',
            product_title: 'Medusa Sweatshirt',
            product_description:
              'Reimagine the feeling of a classic sweatshirt. With our cotton sweatshirt, everyday essentials no longer have to be ordinary.',
            product_subtitle: null,
            product_type: null,
            product_type_id: null,
            product_collection: null,
            product_handle: 'sweatshirt',
            variant_sku: 'SWEATSHIRT-M',
            variant_barcode: null,
            variant_title: 'M',
            variant_option_values: null,
            requires_shipping: true,
            is_discountable: true,
            is_tax_inclusive: false,
            is_custom_price: false,
            metadata: {},
            raw_compare_at_unit_price: null,
            raw_unit_price: {
              value: '10',
              precision: 20,
            },
            created_at: '2025-03-28T07:43:17.839Z',
            updated_at: '2025-03-28T07:43:17.840Z',
            deleted_at: null,
            tax_lines: [],
            adjustments: [],
            compare_at_unit_price: null,
            unit_price: 10,
            quantity: 1,
            raw_quantity: {
              value: '1',
              precision: 20,
            },
            detail: {
              id: 'orditem_01JQE2P1F9G6MPGVY4D2PW0CJP',
              version: 2,
              metadata: null,
              order_id: 'order_01JQDV93AEHJ6VNSCE13EWYTB1',
              raw_unit_price: {
                value: '10',
                precision: 20,
              },
              raw_compare_at_unit_price: null,
              raw_quantity: {
                value: '1',
                precision: 20,
              },
              raw_fulfilled_quantity: {
                value: '1',
                precision: 20,
              },
              raw_delivered_quantity: {
                value: '0',
                precision: 20,
              },
              raw_shipped_quantity: {
                value: '0',
                precision: 20,
              },
              raw_return_requested_quantity: {
                value: '0',
                precision: 20,
              },
              raw_return_received_quantity: {
                value: '0',
                precision: 20,
              },
              raw_return_dismissed_quantity: {
                value: '0',
                precision: 20,
              },
              raw_written_off_quantity: {
                value: '0',
                precision: 20,
              },
              created_at: '2025-03-28T09:52:41.968Z',
              updated_at: '2025-03-28T09:52:41.968Z',
              deleted_at: null,
              item_id: 'ordli_01JQDV93AEZSQSXHMHEMQWTG5G',
              unit_price: 10,
              compare_at_unit_price: null,
              quantity: 1,
              fulfilled_quantity: 1,
              delivered_quantity: 0,
              shipped_quantity: 0,
              return_requested_quantity: 0,
              return_received_quantity: 0,
              return_dismissed_quantity: 0,
              written_off_quantity: 0,
            },
            subtotal: 10,
            total: 10,
            original_total: 10,
            discount_total: 0,
            discount_subtotal: 0,
            discount_tax_total: 0,
            tax_total: 0,
            original_tax_total: 0,
            refundable_total_per_unit: 10,
            refundable_total: 10,
            fulfilled_total: 10,
            shipped_total: 0,
            return_requested_total: 0,
            return_received_total: 0,
            return_dismissed_total: 0,
            write_off_total: 0,
            raw_subtotal: {
              value: '10',
              precision: 20,
            },
            raw_total: {
              value: '10',
              precision: 20,
            },
            raw_original_total: {
              value: '10',
              precision: 20,
            },
            raw_discount_total: {
              value: '0',
              precision: 20,
            },
            raw_discount_subtotal: {
              value: '0',
              precision: 20,
            },
            raw_discount_tax_total: {
              value: '0',
              precision: 20,
            },
            raw_tax_total: {
              value: '0',
              precision: 20,
            },
            raw_original_tax_total: {
              value: '0',
              precision: 20,
            },
            raw_refundable_total_per_unit: {
              value: '10',
              precision: 20,
            },
            raw_refundable_total: {
              value: '10',
              precision: 20,
            },
            raw_fulfilled_total: {
              value: '10',
              precision: 20,
            },
            raw_shipped_total: {
              value: '0',
              precision: 20,
            },
            raw_return_requested_total: {
              value: '0',
              precision: 20,
            },
            raw_return_received_total: {
              value: '0',
              precision: 20,
            },
            raw_return_dismissed_total: {
              value: '0',
              precision: 20,
            },
            raw_write_off_total: {
              value: '0',
              precision: 20,
            },
          },
        ],
        customer: {
          id: 'cus_01JQDTPXX68AHZFH610641WZM2',
          company_name: null,
          first_name: 'Peter',
          last_name: 'Demo1',
          email: 'peter@gmail.com',
          phone: '0414949323',
          has_account: true,
          metadata: null,
          created_by: null,
          created_at: '2025-03-28T07:33:22.471Z',
          updated_at: '2025-03-28T07:33:22.471Z',
          deleted_at: null,
        },
        sales_channel: {
          id: 'sc_01JQDTGY0BDTYDQN9FZYKMD5Q1',
          name: 'Default Sales Channel',
          description: 'Created by Medusa',
          is_disabled: false,
          metadata: null,
          created_at: '2025-03-28T07:30:05.964Z',
          updated_at: '2025-03-28T07:30:05.964Z',
          deleted_at: null,
        },
        payment_status: 'captured',
        fulfillment_status: 'fulfilled',
      },
    ],
    count: 1,
    offset: 0,
    limit: 10,
    status: 'success',
    fetchStatus: 'idle',
    isPending: false,
    isSuccess: true,
    isError: false,
    isInitialLoading: false,
    isLoading: false,
    dataUpdatedAt: 1743299640719,
    error: null,
    errorUpdatedAt: 0,
    failureCount: 0,
    failureReason: null,
    errorUpdateCount: 0,
    isFetched: true,
    isFetchedAfterMount: true,
    isFetching: false,
    isRefetching: false,
    isLoadingError: false,
    isPaused: false,
    isPlaceholderData: false,
    isRefetchError: false,
    isStale: false,
    promise: {
      status: 'rejected',
      reason: {},
    },
  },
  useDataTableAll: {
    table: {
      _features: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
      options: {
        filterFromLeafRows: false,
        maxLeafRowFilterDepth: 100,
        globalFilterFn: 'auto',
        groupedColumnMode: 'reorder',
        paginateExpandedRows: true,
        enableRowSelection: false,
        enableMultiRowSelection: true,
        enableSubRowSelection: true,
        columnResizeMode: 'onEnd',
        columnResizeDirection: 'ltr',
        state: {
          columnSizing: {},
          columnSizingInfo: {
            startOffset: null,
            startSize: null,
            deltaOffset: null,
            deltaPercentage: null,
            isResizingColumn: false,
            columnSizingStart: [],
          },
          rowSelection: {},
          rowPinning: {
            top: [],
            bottom: [],
          },
          expanded: {},
          grouping: [],
          sorting: [],
          columnFilters: [],
          columnPinning: {
            left: [],
            right: [],
          },
          columnOrder: [],
          columnVisibility: {},
          pagination: {
            pageIndex: 0,
            pageSize: 10,
          },
        },
        renderFallbackValue: null,
        data: [
          {
            id: 'order_01JQDV93AEHJ6VNSCE13EWYTB1',
            status: 'pending',
            display_id: 1,
            created_at: '2025-03-28T07:43:17.839Z',
            email: 'peter@gmail.com',
            total: 30,
            currency_code: 'eur',
            version: 2,
            customer_id: 'cus_01JQDTPXX68AHZFH610641WZM2',
            sales_channel_id: 'sc_01JQDTGY0BDTYDQN9FZYKMD5Q1',
            items: [
              {
                id: 'ordli_01JQDV93AERP766VZB13PXHXYE',
                title: 'XL',
                subtitle: 'Medusa Shorts',
                thumbnail: 'https://medusa-public-images.s3.eu-west-1.amazonaws.com/shorts-vintage-front.png',
                variant_id: 'variant_01JQDTH05M2QKQ3T0HCF691XWR',
                product_id: 'prod_01JQDTH04AMRGFM5GRE9DVT7XQ',
                product_title: 'Medusa Shorts',
                product_description:
                  'Reimagine the feeling of classic shorts. With our cotton shorts, everyday essentials no longer have to be ordinary.',
                product_subtitle: null,
                product_type: null,
                product_type_id: null,
                product_collection: null,
                product_handle: 'shorts',
                variant_sku: 'SHORTS-XL',
                variant_barcode: null,
                variant_title: 'XL',
                variant_option_values: null,
                requires_shipping: true,
                is_discountable: true,
                is_tax_inclusive: false,
                is_custom_price: false,
                metadata: {},
                raw_compare_at_unit_price: null,
                raw_unit_price: {
                  value: '10',
                  precision: 20,
                },
                created_at: '2025-03-28T07:43:17.840Z',
                updated_at: '2025-03-28T07:43:17.840Z',
                deleted_at: null,
                tax_lines: [],
                adjustments: [],
                compare_at_unit_price: null,
                unit_price: 10,
                quantity: 1,
                raw_quantity: {
                  value: '1',
                  precision: 20,
                },
                detail: {
                  id: 'orditem_01JQE2P1F98JPTQ14JJQWTTZAS',
                  version: 2,
                  metadata: null,
                  order_id: 'order_01JQDV93AEHJ6VNSCE13EWYTB1',
                  raw_unit_price: {
                    value: '10',
                    precision: 20,
                  },
                  raw_compare_at_unit_price: null,
                  raw_quantity: {
                    value: '1',
                    precision: 20,
                  },
                  raw_fulfilled_quantity: {
                    value: '1',
                    precision: 20,
                  },
                  raw_delivered_quantity: {
                    value: '0',
                    precision: 20,
                  },
                  raw_shipped_quantity: {
                    value: '0',
                    precision: 20,
                  },
                  raw_return_requested_quantity: {
                    value: '0',
                    precision: 20,
                  },
                  raw_return_received_quantity: {
                    value: '0',
                    precision: 20,
                  },
                  raw_return_dismissed_quantity: {
                    value: '0',
                    precision: 20,
                  },
                  raw_written_off_quantity: {
                    value: '0',
                    precision: 20,
                  },
                  created_at: '2025-03-28T09:52:41.968Z',
                  updated_at: '2025-03-28T09:52:41.968Z',
                  deleted_at: null,
                  item_id: 'ordli_01JQDV93AERP766VZB13PXHXYE',
                  unit_price: 10,
                  compare_at_unit_price: null,
                  quantity: 1,
                  fulfilled_quantity: 1,
                  delivered_quantity: 0,
                  shipped_quantity: 0,
                  return_requested_quantity: 0,
                  return_received_quantity: 0,
                  return_dismissed_quantity: 0,
                  written_off_quantity: 0,
                },
                subtotal: 10,
                total: 10,
                original_total: 10,
                discount_total: 0,
                discount_subtotal: 0,
                discount_tax_total: 0,
                tax_total: 0,
                original_tax_total: 0,
                refundable_total_per_unit: 10,
                refundable_total: 10,
                fulfilled_total: 10,
                shipped_total: 0,
                return_requested_total: 0,
                return_received_total: 0,
                return_dismissed_total: 0,
                write_off_total: 0,
                raw_subtotal: {
                  value: '10',
                  precision: 20,
                },
                raw_total: {
                  value: '10',
                  precision: 20,
                },
                raw_original_total: {
                  value: '10',
                  precision: 20,
                },
                raw_discount_total: {
                  value: '0',
                  precision: 20,
                },
                raw_discount_subtotal: {
                  value: '0',
                  precision: 20,
                },
                raw_discount_tax_total: {
                  value: '0',
                  precision: 20,
                },
                raw_tax_total: {
                  value: '0',
                  precision: 20,
                },
                raw_original_tax_total: {
                  value: '0',
                  precision: 20,
                },
                raw_refundable_total_per_unit: {
                  value: '10',
                  precision: 20,
                },
                raw_refundable_total: {
                  value: '10',
                  precision: 20,
                },
                raw_fulfilled_total: {
                  value: '10',
                  precision: 20,
                },
                raw_shipped_total: {
                  value: '0',
                  precision: 20,
                },
                raw_return_requested_total: {
                  value: '0',
                  precision: 20,
                },
                raw_return_received_total: {
                  value: '0',
                  precision: 20,
                },
                raw_return_dismissed_total: {
                  value: '0',
                  precision: 20,
                },
                raw_write_off_total: {
                  value: '0',
                  precision: 20,
                },
              },
              {
                id: 'ordli_01JQDV93AEZSQSXHMHEMQWTG5G',
                title: 'M',
                subtitle: 'Medusa Sweatshirt',
                thumbnail: 'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatshirt-vintage-front.png',
                variant_id: 'variant_01JQDTH05M2Y7WAD82ERNY3R90',
                product_id: 'prod_01JQDTH04AZVTP47HQHM0Z83RG',
                product_title: 'Medusa Sweatshirt',
                product_description:
                  'Reimagine the feeling of a classic sweatshirt. With our cotton sweatshirt, everyday essentials no longer have to be ordinary.',
                product_subtitle: null,
                product_type: null,
                product_type_id: null,
                product_collection: null,
                product_handle: 'sweatshirt',
                variant_sku: 'SWEATSHIRT-M',
                variant_barcode: null,
                variant_title: 'M',
                variant_option_values: null,
                requires_shipping: true,
                is_discountable: true,
                is_tax_inclusive: false,
                is_custom_price: false,
                metadata: {},
                raw_compare_at_unit_price: null,
                raw_unit_price: {
                  value: '10',
                  precision: 20,
                },
                created_at: '2025-03-28T07:43:17.839Z',
                updated_at: '2025-03-28T07:43:17.840Z',
                deleted_at: null,
                tax_lines: [],
                adjustments: [],
                compare_at_unit_price: null,
                unit_price: 10,
                quantity: 1,
                raw_quantity: {
                  value: '1',
                  precision: 20,
                },
                detail: {
                  id: 'orditem_01JQE2P1F9G6MPGVY4D2PW0CJP',
                  version: 2,
                  metadata: null,
                  order_id: 'order_01JQDV93AEHJ6VNSCE13EWYTB1',
                  raw_unit_price: {
                    value: '10',
                    precision: 20,
                  },
                  raw_compare_at_unit_price: null,
                  raw_quantity: {
                    value: '1',
                    precision: 20,
                  },
                  raw_fulfilled_quantity: {
                    value: '1',
                    precision: 20,
                  },
                  raw_delivered_quantity: {
                    value: '0',
                    precision: 20,
                  },
                  raw_shipped_quantity: {
                    value: '0',
                    precision: 20,
                  },
                  raw_return_requested_quantity: {
                    value: '0',
                    precision: 20,
                  },
                  raw_return_received_quantity: {
                    value: '0',
                    precision: 20,
                  },
                  raw_return_dismissed_quantity: {
                    value: '0',
                    precision: 20,
                  },
                  raw_written_off_quantity: {
                    value: '0',
                    precision: 20,
                  },
                  created_at: '2025-03-28T09:52:41.968Z',
                  updated_at: '2025-03-28T09:52:41.968Z',
                  deleted_at: null,
                  item_id: 'ordli_01JQDV93AEZSQSXHMHEMQWTG5G',
                  unit_price: 10,
                  compare_at_unit_price: null,
                  quantity: 1,
                  fulfilled_quantity: 1,
                  delivered_quantity: 0,
                  shipped_quantity: 0,
                  return_requested_quantity: 0,
                  return_received_quantity: 0,
                  return_dismissed_quantity: 0,
                  written_off_quantity: 0,
                },
                subtotal: 10,
                total: 10,
                original_total: 10,
                discount_total: 0,
                discount_subtotal: 0,
                discount_tax_total: 0,
                tax_total: 0,
                original_tax_total: 0,
                refundable_total_per_unit: 10,
                refundable_total: 10,
                fulfilled_total: 10,
                shipped_total: 0,
                return_requested_total: 0,
                return_received_total: 0,
                return_dismissed_total: 0,
                write_off_total: 0,
                raw_subtotal: {
                  value: '10',
                  precision: 20,
                },
                raw_total: {
                  value: '10',
                  precision: 20,
                },
                raw_original_total: {
                  value: '10',
                  precision: 20,
                },
                raw_discount_total: {
                  value: '0',
                  precision: 20,
                },
                raw_discount_subtotal: {
                  value: '0',
                  precision: 20,
                },
                raw_discount_tax_total: {
                  value: '0',
                  precision: 20,
                },
                raw_tax_total: {
                  value: '0',
                  precision: 20,
                },
                raw_original_tax_total: {
                  value: '0',
                  precision: 20,
                },
                raw_refundable_total_per_unit: {
                  value: '10',
                  precision: 20,
                },
                raw_refundable_total: {
                  value: '10',
                  precision: 20,
                },
                raw_fulfilled_total: {
                  value: '10',
                  precision: 20,
                },
                raw_shipped_total: {
                  value: '0',
                  precision: 20,
                },
                raw_return_requested_total: {
                  value: '0',
                  precision: 20,
                },
                raw_return_received_total: {
                  value: '0',
                  precision: 20,
                },
                raw_return_dismissed_total: {
                  value: '0',
                  precision: 20,
                },
                raw_write_off_total: {
                  value: '0',
                  precision: 20,
                },
              },
            ],
            customer: {
              id: 'cus_01JQDTPXX68AHZFH610641WZM2',
              company_name: null,
              first_name: 'Peter',
              last_name: 'Demo1',
              email: 'peter@gmail.com',
              phone: '0414949323',
              has_account: true,
              metadata: null,
              created_by: null,
              created_at: '2025-03-28T07:33:22.471Z',
              updated_at: '2025-03-28T07:33:22.471Z',
              deleted_at: null,
            },
            sales_channel: {
              id: 'sc_01JQDTGY0BDTYDQN9FZYKMD5Q1',
              name: 'Default Sales Channel',
              description: 'Created by Medusa',
              is_disabled: false,
              metadata: null,
              created_at: '2025-03-28T07:30:05.964Z',
              updated_at: '2025-03-28T07:30:05.964Z',
              deleted_at: null,
            },
            payment_status: 'captured',
            fulfillment_status: 'fulfilled',
          },
        ],
        columns: [
          {
            accessorKey: 'display_id',
          },
          {
            accessorKey: 'created_at',
          },
          {
            accessorKey: 'sales_channel',
          },
          {
            accessorKey: 'payment_status',
          },
          {
            accessorKey: 'fulfillment_status',
          },
          {
            accessorKey: 'total',
          },
          {
            id: 'actions',
          },
          {
            id: 'actions',
          },
        ],
        pageCount: 1,
        manualPagination: true,
      },
      initialState: {
        columnSizing: {},
        columnSizingInfo: {
          startOffset: null,
          startSize: null,
          deltaOffset: null,
          deltaPercentage: null,
          isResizingColumn: false,
          columnSizingStart: [],
        },
        rowSelection: {},
        rowPinning: {
          top: [],
          bottom: [],
        },
        expanded: {},
        grouping: [],
        sorting: [],
        columnFilters: [],
        columnPinning: {
          left: [],
          right: [],
        },
        columnOrder: [],
        columnVisibility: {},
        pagination: {
          pageIndex: 0,
          pageSize: 10,
        },
      },
    },
  },
};

export const data = {
  id: 'cus_01JQDTPXX68AHZFH610641WZM2',
  company_name: null,
  first_name: 'Peter',
  last_name: 'Demo1',
  email: 'peter@gmail.com',
  phone: '0414949323',
  metadata: null,
  has_account: true,
  created_by: null,
  created_at: '2025-03-28T07:33:22.471Z',
  updated_at: '2025-03-28T07:33:22.471Z',
  deleted_at: null,
  addresses: [
    {
      id: 'cuaddr_01JQDTR2S3VJ2QSD31CH59A9HX',
      address_name: null,
      is_default_shipping: true,
      is_default_billing: false,
      company: '',
      first_name: 'Peter',
      last_name: 'Demo1',
      address_1: '41 Chuter Avenue',
      address_2: '',
      city: 'Sydney',
      country_code: 'gb',
      province: 'NSW',
      postal_code: '2217',
      phone: '0414949323',
      metadata: null,
      customer_id: 'cus_01JQDTPXX68AHZFH610641WZM2',
      created_at: '2025-03-28T07:34:00.228Z',
      updated_at: '2025-03-28T07:34:00.228Z',
      deleted_at: null,
    },
    {
      id: 'cuaddr_01JQHWT6ET81NSNR2M6599QWZA',
      address_name: 'Sydney',
      is_default_shipping: false,
      is_default_billing: false,
      company: '',
      first_name: null,
      last_name: null,
      address_1: 'Montery Street',
      address_2: '',
      city: '',
      country_code: 'au',
      province: '',
      postal_code: '',
      phone: '',
      metadata: null,
      customer_id: 'cus_01JQDTPXX68AHZFH610641WZM2',
      created_at: '2025-03-29T21:27:04.410Z',
      updated_at: '2025-03-29T21:27:04.410Z',
      deleted_at: null,
    },
  ],
};

export const initialData = {
  customer: {
    id: 'cus_01JQDTPXX68AHZFH610641WZM2',
    company_name: null,
    first_name: 'Peter',
    last_name: 'Demo1',
    email: 'peter@gmail.com',
    phone: '0414949323',
    metadata: null,
    has_account: true,
    created_by: null,
    created_at: '2025-03-28T07:33:22.471Z',
    updated_at: '2025-03-28T07:33:22.471Z',
    deleted_at: null,
    addresses: [
      {
        id: 'cuaddr_01JQDTR2S3VJ2QSD31CH59A9HX',
        address_name: null,
        is_default_shipping: true,
        is_default_billing: false,
        company: '',
        first_name: 'Peter',
        last_name: 'Demo1',
        address_1: '41 Chuter Avenue',
        address_2: '',
        city: 'Sydney',
        country_code: 'gb',
        province: 'NSW',
        postal_code: '2217',
        phone: '0414949323',
        metadata: null,
        customer_id: 'cus_01JQDTPXX68AHZFH610641WZM2',
        created_at: '2025-03-28T07:34:00.228Z',
        updated_at: '2025-03-28T07:34:00.228Z',
        deleted_at: null,
      },
      {
        id: 'cuaddr_01JQHWT6ET81NSNR2M6599QWZA',
        address_name: 'Sydney',
        is_default_shipping: false,
        is_default_billing: false,
        company: '',
        first_name: null,
        last_name: null,
        address_1: 'Montery Street',
        address_2: '',
        city: '',
        country_code: 'au',
        province: '',
        postal_code: '',
        phone: '',
        metadata: null,
        customer_id: 'cus_01JQDTPXX68AHZFH610641WZM2',
        created_at: '2025-03-29T21:27:04.410Z',
        updated_at: '2025-03-29T21:27:04.410Z',
        deleted_at: null,
      },
    ],
  },
};

export const getWidgets = {
  'customer.details.after': [],
  'customer.details.before': [],
  'customer.details.side.after': [],
  'customer.details.side.before': [],
};

export const useOrders = (query: any, options: any) => {
  return captureCustomerOrders.useOrdersAll;
};
